version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - npm install npm@latest -g
      - echo Running NPM setup
      - npm config set '@mitel:registry' https://depot.mitel.io/artifactory/api/npm/mitel/
      - cd deployment/setup-npm
      - npm ci
      - npm run setup-npm -- --role-arn $paramRoleArn --region $AWS_REGION
      - cd ../..
  pre_build:
    commands:
      - echo Installing packages for deployment
      - cd deployment
      - npm ci
      - cd ..
  build:
    commands:
      - echo Starting golive process on `date`
      - cd deployment
      - npm config set cloudlink-auth-portal:region $AWS_REGION
      - npm config set cloudlink-auth-portal:cloud $cloudType
      - npm config set cloudlink-auth-portal:awsrolearn $deployRoleArn
      - npm config set cloudlink-auth-portal:awsprofile ''
      - npm run go-live
      - cd ..
      - echo Build and golive completed on `date`